version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    working_dir: /home/app
    environment:
      - NODE_ENV=production
