# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Front-end & Back-end | Build & Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build
        run: npm run build --if-present
        working-directory: frontend

      - name: Test
        run: npm run test:headless --if-present
        working-directory: frontend

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Build
        run: npm run server:build --if-present
        working-directory: ./backend
