# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Front-end & Back-end | Build & Tests

on:
  # Executa em pushes direcionados ao branch main
  push:
    branches: ["main"]
  # Executa em pull request direcionados ao branch main
  pull_request:
    branches: ["main"]
  # Permite que você execute este fluxo de trabalho manualmente na guia Ações fluxo de trabalho_dispatch:
  workflow_dispatch:

jobs:
  frontend:
    # Define o sistema operacional em que o trabalho será executado
    runs-on: ubuntu-latest
    steps:
      # Acessar o repositório
      - uses: actions/checkout@v4
      # Instalar e usar a versão 20.9.0 do Node.js
      - name: Use Node.js 20.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Build
        run: npm run build:production --if-present
        working-directory: frontend

      - name: Test
        run: npm run test:headless --if-present
        working-directory: frontend

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Build
        run: npm run server:build --if-present
        working-directory: ./backend
